
export const CUISINE_ITEMS=[
  { id: "1", name: "North Indian" },
  { id: "2", name: "Chinese" },
  { id: "3", name: "Fast Food" },
  { id: "4", name: "South Indian" },
  { id: "5", name: "Biryani" },
  { id: "6", name: "Pizza" },
  { id: "7", name: "Bakery" },
  { id: "8", name: "Street Food" },
  { id: "9", name: "Burger" },
  { id: "10", name: "Mughlai" },
  { id: "11", name: "Momos" },
  { id: "12", name: "Sandwich" },
  { id: "13", name: "Mithai" },
  { id: "14", name: "Rolls" },
  { id: "15", name: "Beverages" },
  { id: "16", name: "Desserts" },
  { id: "17", name: "Cafe" },
  { id: "18", name: "Healthy Food" },
  { id: "19", name: "Maharashtrian" },
  { id: "20", name: "Tea" },
  { id: "21", name: "Bengali" },
  { id: "22", name: "Ice Cream" },
  { id: "23", name: "Juices" },
  { id: "24", name: "Shake" },
  { id: "25", name: "Shawarma" },
  { id: "26", name: "Gujarati" },
  { id: "27", name: "Italian" },
  { id: "28", name: "Continental" },
  { id: "29", name: "Lebanese" },
  { id: "30", name: "Salad" },
  { id: "31", name: "Andhra" },
  { id: "32", name: "Waffle" },
  { id: "33", name: "Coffee" },
  { id: "34", name: "Kebab" },
  { id: "35", name: "Arabian" },
  { id: "36", name: "Kerala" },
  { id: "37", name: "Asian" },
  { id: "38", name: "Seafood" },
  { id: "39", name: "Pasta" },
  { id: "40", name: "BBQ" },
  { id: "41", name: "Rajasthani" },
  { id: "42", name: "Wraps" },
  { id: "43", name: "Paan" },
  { id: "44", name: "Hyderabadi" },
  { id: "45", name: "Mexican" },
  { id: "46", name: "Bihari" },
  { id: "47", name: "Goan" },
  { id: "48", name: "Assamese" },
  { id: "49", name: "American" },
  { id: "50", name: "Mandi" },
  { id: "51", name: "Chettinad" },
  { id: "52", name: "Mishti" },
  { id: "53", name: "Bar Food" },
  { id: "54", name: "Malwani" },
  { id: "55", name: "Odia" },
  { id: "56", name: "Roast Chicken" },
  { id: "57", name: "Tamil" },
  { id: "58", name: "Japanese" },
  { id: "59", name: "Finger Food" },
  { id: "60", name: "Korean" },
  { id: "61", name: "North Eastern" },
  { id: "62", name: "Thai" },
  { id: "63", name: "Kathiyawadi" },
  { id: "64", name: "Bubble Tea" },
  { id: "65", name: "Mangalorean" },
  { id: "66", name: "Burmese" },
  { id: "67", name: "Sushi" },
  { id: "68", name: "Lucknowi" },
  { id: "69", name: "Modern Indian" },
  { id: "70", name: "Tibetan" },
  { id: "71", name: "Afghan" },
  { id: "72", name: "Oriental" },
  { id: "73", name: "Pancake" },
  { id: "74", name: "Kashmiri" },
  { id: "75", name: "Middle Eastern" },
  { id: "76", name: "Grocery" },
  { id: "77", name: "Konkan" },
  { id: "78", name: "European" },
  { id: "79", name: "Awadhi" },
  { id: "80", name: "Hot dogs" },
  { id: "81", name: "Sindhi" },
  { id: "82", name: "Turkish" },
  { id: "83", name: "Naga" },
  { id: "84", name: "Mediterranean" },
  { id: "85", name: "Nepalese" },
  { id: "86", name: "Cuisine Varies" },
  { id: "87", name: "Saoji" },
  { id: "88", name: "Charcoal Chicken" },
  { id: "89", name: "Steak" },
  { id: "90", name: "Frozen Yogurt" },
  { id: "91", name: "Panini" },
  { id: "92", name: "Parsi" },
  { id: "93", name: "Sichuan" },
  { id: "94", name: "Iranian" },
  { id: "95", name: "Grilled Chicken" },
  { id: "96", name: "French" },
  { id: "97", name: "Raw Meats" },
  { id: "98", name: "Drinks Only" },
  { id: "99", name: "Vietnamese" },
  { id: "100", name: "Liquor" },
  { id: "101", name: "Greek" },
  { id: "102", name: "Himachali" },
  { id: "103", name: "Bohri" },
  { id: "104", name: "Garhwali" },
  { id: "105", name: "Cantonese" },
  { id: "106", name: "Malaysian" },
  { id: "107", name: "Belgian" },
  { id: "108", name: "British" },
  { id: "109", name: "African" },
  { id: "110", name: "Spanish" },
  { id: "111", name: "Manipuri" },
  { id: "112", name: "Egyptian" },
  { id: "113", name: "Sri Lankan" },
  { id: "114", name: "Relief fund" },
  { id: "115", name: "Bangladeshi" },
  { id: "116", name: "Indonesian" },
  { id: "117", name: "Tex-Mex" },
  { id: "118", name: "Irish" },
  { id: "119", name: "Singaporean" },
  { id: "120", name: "South American" },
  { id: "121", name: "Mongolian" },
  { id: "122", name: "German" },
  { id: "123", name: "Russian" },
  { id: "124", name: "Brazilian" },
  { id: "125", name: "Pakistani" },
  { id: "126", name: "Australian" },
  { id: "127", name: "Moroccan" },
  { id: "128", name: "Filipino" },
  { id: "129", name: "Hot Pot" },
  { id: "130", name: "Retail Products" },
  { id: "131", name: "Mizo" },
  { id: "132", name: "Portuguese" },
  { id: "133", name: "Indian" },
  { id: "134", name: "Tripuri" },
  { id: "135", name: "Delight Goodies" },
  { id: "136", name: "Meghalayan" },
  { id: "137", name: "Sikkimese" },
  { id: "138", name: "Armenian" },
  { id: "139", name: "Afghani" },
];
export const days = [
  {
    id: "sunday",
    label: "sunday",
  },
  {
    id: "monday",
    label: "monday",
  },
  {
    id: "tuesday",
    label: "tuesday",
  },
  {
    id: "wednesday",
    label: "wednesday",
  },
  {
    id: "thursday",
    label: "thursday",
  },
  {
    id: "friday",
    label: "friday",
  },
  {
    id: "saturday",
    label: "saturday",
  },
];

