import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";
import { NextResponse } from "next/server";
import QRCode from "qrcode";

export async function POST(req: Request) {
  try {
    const session = await auth();
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    if (
      session.user.role !== "ADMIN" &&
      session.user.role !== "RESTAURANT_OWNER"
    ) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { number } = await req.json();
    if (!number) {
      return NextResponse.json(
        { error: "Table number required" },
        { status: 400 }
      );
    }

    const restaurant = await prisma.restaurantStep1.findFirst({
      where: { userId: session.user.id },
    });

    if (!restaurant) {
      return NextResponse.json(
        { error: "Restaurant not found" },
        { status: 404 }
      );
    }

    // ✅ Create table (ID auto-generated by Prisma)
    const table = await prisma.table.create({
      data: {
        number,
        qrCodeUrl: "",
        restaurantId: restaurant.id,
      },
    });

    const qrLink = `${process.env.AUTH_URL}/city/${restaurant.city}/${restaurant.slug}?tableId=${table.id}`;

    const qrCodeUrl = await QRCode.toDataURL(qrLink);

    const updatedTable = await prisma.table.update({
      where: { id: table.id },
      data: { qrCodeUrl },
    });

    return NextResponse.json(updatedTable, { status: 201 });
  } catch (error) {
    console.error("TABLE_CREATE_ERROR", error);
    return NextResponse.json({ error: "Server Error" }, { status: 500 });
  }
}

export async function GET() {
  try {
    const session = await auth();
    if (!session) return NextResponse.json([], { status: 200 });

    if (session.user.role !== "ADMIN" && session.user.role !== "RESTAURANT_OWNER") {
      return NextResponse.json([], { status: 200 });
    }

    const restaurant = await prisma.restaurantStep1.findFirst({
      where: { userId: session.user.id },
    });

    if (!restaurant) return NextResponse.json([], { status: 200 });

    const tables = await prisma.table.findMany({
      where: { restaurantId: restaurant.id },
      orderBy: { number: "asc" },
    });

    return NextResponse.json(tables, { status: 200 });
  } catch {
    return NextResponse.json([], { status: 500 });
  }
}
